[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
merkle = "4ekk1PnQEv3ak6kv88UChc1uc7769FgMNgdgT5h5m3qB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://localhost:8899" #cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
